<x-layouts.app>
    <section class="relative overflow-hidden bg-navy py-20 lg:min-h-[680px] lg:py-28"><div class="absolute inset-y-0 left-0 hidden w-1/3 opacity-20 lg:block" style="background:repeating-radial-gradient(ellipse at bottom left,transparent 0 25px,#B89A5E 27px 28px,transparent 30px 55px)"></div><div class="shell relative grid items-end gap-12 lg:grid-cols-[1.25fr_.75fr]"><div><p class="eyebrow">الإسكندرية · داخل مصر وخارجها</p><h1 class="mt-5 max-w-3xl font-serif text-5xl leading-[1.2] text-white md:text-6xl xl:text-7xl">حلول قانونية واضحة لحماية مصالحك</h1><p class="mt-7 max-w-2xl text-lg leading-9 text-stone">يقدم مكتب مروان الهواري للمحاماة والاستشارات القانونية خدمات متخصصة للأفراد والشركات، من خلال دراسة دقيقة لكل ملف ومشورة عملية وتمثيل قانوني يتسم بالكفاءة والمهنية.</p><div class="mt-9 flex flex-wrap gap-3"><a href="{{route('contact')}}" class="btn btn-gold inline-flex">احجز استشارتك القانونية</a><a href="{{route('practice-areas')}}" class="btn btn-outline inline-flex">تعرّف على خدماتنا</a></div></div><aside class="border-r-2 border-gold bg-white/5 p-7 backdrop-blur-sm"><p class="text-sm leading-8 text-stone">نُعالج كل ملف بمنهج واضح، مع عناية بالتفاصيل وخصوصية التواصل.</p><ul class="mt-7 space-y-4 text-sm text-white"><li>خدمات للأفراد والشركات</li><li>تمثيل أمام المحاكم وهيئات التحكيم</li><li>خدمات داخل مصر وخارجها</li></ul></aside></div></section>
    <section class="py-20"><div class="shell grid gap-10 lg:grid-cols-2 lg:items-center"><x-section-heading eyebrow="عن المكتب" title="خبرة قانونية قائمة على الدقة والالتزام" text="مكتب متخصص في تقديم الخدمات والاستشارات القانونية للأفراد والشركات في مجالات متنوعة، من الإسكندرية وللعملاء داخل مصر وخارجها."/><div class="border-r-2 border-gold bg-white p-8 leading-9 text-muted shadow-sm">نعمل على فهم احتياجات كل عميل، ودراسة تفاصيل ملفه بعناية، ثم تقديم حلول قانونية واضحة وعملية تساعده على حماية حقوقه واتخاذ قراراته بثقة.<a class="mt-5 block font-bold text-navy" href="{{route('about')}}">المزيد عن المكتب ←</a></div></div></section>
    <section class="bg-stone/45 py-20"><div class="shell"><x-section-heading eyebrow="الخدمات القانونية" title="مجالات الممارسة القانونية" text="استشارات متخصصة واستراتيجية مناسبة لطبيعة كل ملف واحتياجات كل عميل."/><div class="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">@foreach(config('lawoffice.practices') as $slug=>$practice) @if($practice['featured'])<x-practice-card :slug="$slug" :practice="$practice"/>@endif @endforeach</div><a href="{{route('practice-areas')}}" class="mt-8 inline-flex font-bold text-navy">عرض جميع مجالات الممارسة ←</a></div></section>
    <section class="py-20"><div class="shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div class="min-h-80 bg-charcoal p-8 text-white"><p class="eyebrow">المحامي المؤسس</p><p class="mt-20 font-serif text-4xl leading-tight">{{config('lawoffice.founder.name')}}</p></div><div><x-section-heading title="تمثيل قانوني يقوم على المهنية والوضوح" text="يحرص الأستاذ مروان الهواري على دراسة كل ملف بصورة دقيقة، وتقديم المشورة القانونية الواضحة، وتمثيل العملاء بكفاءة أمام المحاكم والجهات القضائية وهيئات التحكيم."/><div class="mt-8 flex flex-wrap gap-3">@foreach(config('lawoffice.founder.qualifications') as $item)<span class="border border-stone bg-white px-4 py-2 text-sm text-navy">{{ $item }}</span>@endforeach</div><a class="mt-8 inline-flex font-bold text-navy" href="{{route('founder')}}">تعرّف على المحامي المؤسس ←</a></div></div></section>
    <section class="bg-charcoal py-20"><div class="shell"><x-section-heading light eyebrow="لماذا نحن" title="علاقة قانونية تقوم على الثقة" text="نؤمن أن جودة العمل القانوني تبدأ من الاستماع الجيد والفهم الدقيق وتقديم مشورة مسؤولة."/><div class="mt-10 grid gap-px bg-white/10 md:grid-cols-4">@foreach(config('lawoffice.values') as $i=>$value)<div class="bg-charcoal p-6"><span class="text-gold">0{{$i+1}}</span><h3 class="mt-7 font-serif text-xl text-white">{{$value}}</h3></div>@endforeach</div></div></section>
    <section id="faq" class="py-20"><div class="shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><x-section-heading eyebrow="إجابات واضحة" title="الأسئلة الشائعة" text="إجابات عامة تساعدك على معرفة طريقة التواصل والخدمات المتاحة."/><div>@foreach(config('lawoffice.faq') as $index=>$item)<x-faq-item :item="$item" :index="$index"/>@endforeach</div></div></section>
    <x-consultation-banner />
</x-layouts.app>
